import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { getUserData } from '../redux/user';
import { useSelector, useDispatch } from 'react-redux';
import { AiOutlineLoading3Quarters } from 'react-icons/ai';
import { CiCircleChevLeft, CiCircleChevRight } from 'react-icons/ci';

const Home = () => {
	const dispatch = useDispatch();
	const [dataLoaded, setDataLoaded] = useState(false);
	const [users, setUsers] = useState([]);
	const [currentUser, setCurrentUser] = useState([]);
	const [page, setPage] = useState(1);
	const totalPages = users.total_pages;

	useEffect(() => {
		fetch(`https://reqres.in/api/users?page=${page}`)
			.then(res => res.json())
			.then(json => {
				setUsers(json);
				// dispatch(getUserData(users?.data));
				setDataLoaded(true);
			});
	}, [page]);

	const getUserData = id => {
		fetch(`https://reqres.in/api/users/${id}`)
			.then(res => res.json())
			.then(json => {
				setCurrentUser(json);
			});
	};

	return (
		<>
			<Head>
				<title>Convin Ai</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-full h-screen bg-indigo-200 flex flex-col justify-center items-center">
				{dataLoaded ? (
					<div className="w-full flex flex-col justify-center items-center">
						{currentUser?.data ? (
							<div className="bg-white w-2/3 md:w-1/3 h-56 shadow-indigo-500/40 py-3 rounded-lg flex flex-col justify-center items-center">
								<Image
									className="rounded-full shadow-xl my-2"
									src={currentUser.data?.avatar}
									width={70}
									height={70}
								/>
								<div className="text-xl font-semibold">
									{currentUser.data?.first_name}{' '}
									{currentUser.data?.last_name}
								</div>
								<div className="text-slate-600 pt-3">
									{currentUser.data?.email}
								</div>
								<div className="text-slate-600 text-sm font-regular">
									User id : {currentUser.data?.id}
								</div>
							</div>
						) : (
							<div className="bg-white w-2/3 md:w-1/3 h-56 rounded-lg flex flex-col justify-center items-center">
								Select any button 👇
							</div>
						)}

						<div className="flex my-4 md:my-0">
							{users?.data?.map(item => (
								<div
									onClick={() => getUserData(item.id)}
									className="bg-green-500 text-white rounded-lg shadow-indigo-500/40 h-4 w-4 p-5 m-1 md:m-5 flex justify-center items-center cursor-pointer "
								>
									{item.id}
								</div>
							))}
						</div>
						<div className="flex mt-6">
							<div className="flex justify-center items-center">
								<CiCircleChevLeft
									size={30}
									color="#fff"
									className="cursor-pointer"
									onClick={() => {
										if (page > 1) setPage(page - 1);
									}}
								/>
							</div>
							<div className="px-4 flex items-center">
								Page : {page}
							</div>
							<div className="flex justify-center items-center">
								<CiCircleChevRight
									size={30}
									color="#fff"
									className="cursor-pointer"
									onClick={() => {
										if (page < totalPages)
											setPage(page + 1);
									}}
								/>
							</div>
						</div>
					</div>
				) : (
					<>
						<AiOutlineLoading3Quarters
							size={30}
							color="grey"
							className="animate-spin"
						/>
					</>
				)}
			</div>
		</>
	);
};

const UserCard = () => <></>;

export default Home;
